### ISSUE TITLE
Segmentation error after following your instructions

### ISSUE THREAD

**Issue by RollinCajun** [lemogne/omenrgb#1]
I got this error after doing the instructions you have on this github all installed and all went well it even told me to reboot my laptop so I did. I came back and tried to run the app from the directory and I get this error.

./omenrgb
Segmentation fault (core dumped)

I'm on a OMEN by HP Laptop 15-dc1xxx  laptop and using the newest version of Kubuntu 24.04 LTS

Since I switched from windows to linux two days ago I'm already going crazy without my backlighting at night. I sure hope I can get this working somehow. That's the only issue I've come across so far with this laptop all the rest seems to be working great. Ubuntu straight out of the box did great.

**Comment by lemogne** [comment]
Hi,
there were some changes in the kernel recently (I assume) that break the [`hp-omen-linux-module`](https://github.com/pelrun/hp-omen-linux-module) (that this project relies on), and I remember there were issues with it even compiling correctly. I had to change line 1249 to `.remove = (void (*)(struct platform_device *))__exit_p(hp_wmi_bios_remove),` in `hp-wmi.c`. So, if your issue is the same as mine, I recommend just changing the file, running `make uninstall` and then `make install` in the `hp-omen-linux-module` files.

**Comment by RollinCajun** [comment]
> Hi, there were some changes in the kernel recently (I assume) that break the [`hp-omen-linux-module`](https://github.com/pelrun/hp-omen-linux-module) (that this project relies on), and I remember there were issues with it even compiling correctly. I had to change line 1249 to `.remove = (void (*)(struct platform_device *))__exit_p(hp_wmi_bios_remove),` in `hp-wmi.c`. So, if your issue is the same as mine, I recommend just changing the file, running `make uninstall` and then `make install` in the `hp-omen-linux-module` files.

Actually it turns out that it was a permissions issue. For some odd reason when installing your app it didn't set the write permissions on the zone files so when I tried to use the echo command, you gave example on, it wasn't actually changing the color. It was staying 0 0 0. I ended up asking chatgpt for some help and it told me to set the permissions and once I did that as soon as I set a color the keyboard lit up. So for almost a week trying to get it working it was just a permission issue the entire time. I am currently on pop os so older os where before I was on the newest ubuntu. I fell in love with pop os so I have no reason to go back to ubuntu.

**Comment by lemogne** [comment]
Yeah, whoops. I should probably add that to the build script. I forgot that you had to do that for it to work.
Anyway, have fun using Linux!
